#FROM eastuni/apachemodjk
FROM scazadar/apachejk

RUN ls -l /etc/libapache2-mod-jk/workers.properties
RUN cat /etc/libapache2-mod-jk/workers.properties
RUN ls /etc/apache2/
RUN cat /etc/apache2/sites-enabled/000-default.conf


#FROM restcomm/load-balancer:latest
#MAINTAINER andy.dumin@gmail.com
#
#
#RUN ls -l /opt/loadbalancer/config/
#RUN cd /opt/loadbalancer/config/
#RUN cat /opt/loadbalancer/config/lb-configuration.xml
#RUN cat /opt/loadbalancer/config/keystore.jks


